
CREATE DATABASE ApexMercatoe



CREATE TABLE Equipe (
Equipe_id INT PRIMARY KEY AUTO_INCREMENT, 
Nom VARCHAR(20) NOT NULL,
Budget VARCHAR(40) NOT NULL,
Manager VARCHAR(40) NOT NULL
);

CREATE TABLE Joueur(
Joueur_id INT PRIMARY KEY AUTO_INCREMENT,
Equipe_id INT  NOT NULL,
Nom VARCHAR(20) NOT NULL,
Email VARCHAR(50) NOT NULL,
Nationalité VARCHAR(20) NOT NULL,
Pseudo VARCHAR(20) NOT NULL,
Rôle VARCHAR(30) NOT NULL,
Valeur_Marchande INT  NOT NULL, 
FOREIGN KEY (Equipe_id) REFERENCES Equipe(Equipe_id) ON DELETE CASCADE
);

CREATE TABLE Coach  (
Coach_id INT PRIMARY KEY AUTO_INCREMENT,
Equipe_id INT  NOT NULL,
Nom VARCHAR(20) NOT NULL,
Email VARCHAR(50) NOT NULL,
Nationalité VARCHAR(20) NOT NULL
Style_de_coaching VARCHAR(50) NOT NULL,
Années_dexpérience INT NOT NULL,
FOREIGN KEY (Equipe_id) REFERENCES Equipe(Equipe_id) ON DELETE CASCADE
);

CREATE TABLE Contrat  (
Contrat_id INT PRIMARY KEY AUTO_INCREMENT,
Coach_id INT  NOT NULL,
Joueur_id INT  NOT NULL,
Equipe_id INT  NOT NULL,
Salaire int NOT NULL,
Clause_de_rachat decimal (30) NOT NULL,
Date_de_fin date ,
FOREIGN KEY (Equipe_id) REFERENCES Equipe(Equipe_id) ON DELETE CASCADE,
FOREIGN KEY (Coach_id) REFERENCES Coach(Coach_id) ON DELETE CASCADE,
FOREIGN KEY (Joueur_id) REFERENCES Joueur(Joueur_id) ON DELETE CASCADE
);

CREATE TABLE Transfert  (
Contrat_id INT PRIMARY KEY AUTO_INCREMENT,
Joueur_id INT  NOT NULL,
Equipe_départ_id INT  NOT NULL,
Equipe_arrivée_id INT  NOT NULL,
Équipe_départ VARCHAR(40) NOT NULL,
Équipe_arrivée VARCHAR(30) NOT NULL,
Montant int NOT NULL,
Statut VARCHAR(30) NOT NULL,
FOREIGN KEY (Equipe_départ_id) REFERENCES Equipe(Equipe_id) ON DELETE CASCADE,
FOREIGN KEY (Equipe_arrivée_id) REFERENCES Equipe(Equipe_id) ON DELETE CASCADE,
FOREIGN KEY (Joueur_id) REFERENCES Joueur(Joueur_id) ON DELETE CASCADE
);