
CREATE DATABASE ApexMercatoe

CREATE TABLE Personnes(
id INT PRIMARY KEY AUTO_INCREMENT,   
Nom VARCHAR(20) NOT NULL,
Email VARCHAR(50) NOT NULL,
Nationalité VARCHAR(20) NOT NULL
);

CREATE TABLE Equipe (
id INT PRIMARY KEY AUTO_INCREMENT, 
Nom VARCHAR(20) NOT NULL,
Budget int NOT NULL,
Manager VARCHAR(40) NOT NULL
);

CREATE TABLE Joueur(
id INT PRIMARY KEY,
Equipe_id INT  NOT NULL,
Pseudo VARCHAR(20) NOT NULL,
Rôle VARCHAR(30) NOT NULL,
Valeur_Marchande INT  NOT NULL, 
FOREIGN KEY (Equipe_id) REFERENCES Equipe(id) ON DELETE CASCADE,
FOREIGN KEY (id) REFERENCES Personnes(id) ON DELETE CASCADE
)

CREATE TABLE Coach  (
id INT PRIMARY KEY,
Equipe_id INT  NOT NULL,
Style_de_coaching VARCHAR(50) NOT NULL,
Années_dexpérience INT NOT NULL,
FOREIGN KEY (Equipe_id) REFERENCES Equipe(id) ON DELETE CASCADE,
FOREIGN KEY (id) REFERENCES Personnes(id) ON DELETE CASCADE
);

CREATE TABLE Contrat  (
id INT PRIMARY KEY AUTO_INCREMENT,
Personnes_id INT  NOT NULL,
Equipe_id INT  NOT NULL,
Salaire int NOT NULL,
Clause_de_rachat decimal (30) NOT NULL,
Date_de_fin date ,
FOREIGN KEY (Equipe_id) REFERENCES Equipe(id) ON DELETE CASCADE,
FOREIGN KEY (Personnes_id) REFERENCES Personnes(id) ON DELETE CASCADE
);

CREATE TABLE Transfert  (
id INT PRIMARY KEY AUTO_INCREMENT,
Joueur_id INT  NOT NULL,
Equipe_départ_id INT  NOT NULL,
Equipe_arrivée_id INT  NOT NULL,
Montant int NOT NULL,
Statut VARCHAR(30) NOT NULL,
FOREIGN KEY (Equipe_départ_id) REFERENCES Equipe(id) ON DELETE CASCADE,
FOREIGN KEY (Equipe_arrivée_id) REFERENCES Equipe(id) ON DELETE CASCADE,
FOREIGN KEY (Joueur_id) REFERENCES Joueur(id) ON DELETE CASCADE
);